version: '3.9'
services:
  team_document:
    image: zellwegerk/fhnw-teamdocument:latest
    container_name: team_document
    ports:
      - "80:80"
    environment:
      - REACT_APP_BACKEND_BASE=http://team_document_server:8080/api/v1
    depends_on:
      - "team_document_server"
  team_document_server:
    image: zellwegerk/fhnw-document-server:latest
    container_name: team_document_server
    ports:
      - "8080:8080"
    depends_on:
      - "team_document_db"
  team_document_db:
    image: mongo:5.0
    container_name: team_document_db
    ports:
      - "27017:27017"
    environment:
        - MONGO_INITDB_DATABASE=team_document_db
    volumes:
      - mongo-volume:/data/db

volumes:
  mongo-volume:
